# Generated by Django 3.2.9 on 2021-11-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='attribute',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
