# Generated by Django 4.0 on 2021-12-08 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Product', '0007_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_values',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='attribute_values',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='attributes_assoc',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='attributes_assoc',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='coupons_used',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='coupons_used',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='images',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='images',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='payment_gateway',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='payment_gateway',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='product_categories',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='product_categories',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='shipping_method',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='shipping_method',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created_by_user', to='User.user'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='modify_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modify_by_user', to='User.user'),
        ),
    ]
