# Generated by Django 3.2.9 on 2021-11-23 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('banner_path', models.CharField(max_length=255, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner_modify_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(max_length=45)),
                ('subject', models.CharField(max_length=255)),
                ('content', froala_editor.fields.FroalaField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emailtemplate_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emailtemplate_modify_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('conf_key', models.CharField(max_length=45)),
                ('conf_value', models.CharField(max_length=45)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='configuration_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='configuration_modify_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_modify_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('flatpages.flatpage', models.Model),
        ),
        migrations.CreateModel(
            name='Banner_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('image_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.banner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner_images_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modify_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='banner_images_modify_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
